export const CHAR_POOL = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

export const SHUFFLE_CODE_MAX_STEPS = 12
export const SHUFFLE_CODE_STEP_INTERVAL = 35

export const SHUFFLE_TEXT_FRAME_RATE = 30
export const SHUFFLE_TEXT_DELAY_PER_CHAR = 1
export const SHUFFLE_TEXT_DURATION = 2
