<template>
  <div class="lg:pt-[calc(12rem-var(--header-height))] lg:pb-48 text-gray-1000 bg-black">
    <div class="mx-auto w-full px-16 grid lg:grid-cols-[repeat(18,1fr)] lg:gap-5">
      <div class="lg:col-span-6">
        <div class="flex flex-col items-start gap-12 lg:sticky lg:top-[192px]">
          <p class="font-pixel-circle text-gray-1000 leading-none text-5xl xl:text-7xl xl:leading-none font-medium tracking-[-0.1rem] xl:tracking-[-0.2rem] [-webkit-text-stroke:0.02rem_currentColor]">
            <span>Featured</span> <span>sessions</span>
          </p>
          <div>
            <a
              :href="`/ship/${citySlug}/schedule`"
              class="inline-flex items-center justify-center gap-3 h-12 px-5 font-mono uppercase border border-[#343232c0] text-gray-1000 hover:bg-white/10 hover:border-[#555] active:bg-white/10 active:border-[#343232c0] select-none cursor-pointer whitespace-nowrap font-semibold"
            >
              Full schedule
              <svg class="w-4 h-4 shrink-0" viewBox="0 0 16 16" fill="currentColor">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M9.53033 2.21968L9 1.68935L7.93934 2.75001L8.46967 3.28034L12.4393 7.25001H1.75H1V8.75001H1.75H12.4393L8.46967 12.7197L7.93934 13.25L9 14.3107L9.53033 13.7803L14.6036 8.70711C14.9941 8.31659 14.9941 7.68342 14.6036 7.2929L9.53033 2.21968Z"/>
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div class="lg:col-start-7 lg:col-span-11 xl:col-start-8">
        <div>
          <div
            v-for="(session, i) in sessions"
            :key="i"
            class="grid gap-5 grid-cols-[repeat(11,1fr)] border-b border-[#343232c0] py-16 first:pt-0 last:border-b-0 last:pb-0"
          >
            <div class="flex flex-col gap-6 items-start col-span-full lg:col-span-4">
              <h3 class="text-gray-1000 leading-none text-3xl lg:leading-none lg:tracking-[-0.04em] font-medium">{{ session.title }}</h3>
              <div class="text-[18px] font-mono uppercase text-gray-1000">{{ session.time }}</div>
            </div>
            <div class="col-span-full lg:col-start-6 lg:col-span-6 flex flex-col gap-6">
              <p class="font-mono font-normal tracking-normal text-gray-400 text-base leading-normal">{{ session.description }}</p>
              <div class="flex flex-col gap-y-2">
                <div class="flex items-center gap-4">
                  <div class="relative size-9 shrink-0 bg-[#343232c0] rounded-full overflow-hidden">
                    <img
                      :src="session.avatar"
                      :alt="session.speaker"
                      class="rounded-full object-cover w-full h-full"
                    />
                  </div>
                  <p class="font-mono font-normal tracking-normal text-base leading-normal uppercase text-gray-1000">
                    {{ session.speaker }}, <span class="text-gray-500 underline underline-offset-2 decoration-gray-600">{{ session.company }}</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useCityRoute } from '@/composables/useCityRoute'

const { citySlug } = useCityRoute()

const sessions = [
  {
    title: 'Real-time voice agents with ElevenLabs and AI SDK',
    time: '3:05 PM–3:25 PM',
    description: 'Voice is the most natural interface for AI, but building it is hard. This talk shows how you can use ElevenLabs APIs and Vercel\'s AI SDK to build real-time voice agents that listen, reason, and respond.',
    speaker: 'Alex Holt',
    company: 'ElevenLabs',
    avatar: '/third/alex-holt.avif',
  },
  {
    title: 'Building AI agents that generate full Next.js Apps',
    time: '3:30 PM–3:50 PM',
    description: 'Swap github.com for mintlify.com on any repo and get a full docs site generated by AI. This talk breaks down the agent harness built on Vercel Sandbox, from codebase analysis to parallel generation to verifying the output by actually building the Next.js site.',
    speaker: 'Nick Khami',
    company: 'Mintlify',
    avatar: '/third/mike_taylor_deepmind.avif',
  },
]
</script>
