<template>
  <div class="lg:pt-[calc(12rem-var(--header-height))] lg:pb-48 text-gray-1000 bg-black">

    <!-- 左侧标题 + 按钮 -->
    <div class="lg:col-span-6">
      <div class="flex flex-col items-start gap-12 lg:sticky lg:top-[192px]">
        <p
          class="font-pixel-circle text-5xl xl:text-7xl font-medium leading-none tracking-[-0.1rem] xl:tracking-[-0.2rem] [-webkit-text-stroke:0.02rem_currentColor]">
          <span>Featured</span> <span>sessions</span>
        </p>

        <a href="/ship/london/schedule"
          class="inline-flex items-center gap-3 h-12 px-5 font-mono uppercase font-semibold border border-[#343232c0] hover:bg-white/10 hover:border-[#555] active:bg-white/10 cursor-pointer">
          Full schedule
          <svg class="w-4 h-4 shrink-0" viewBox="0 0 16 16" fill="currentColor">
            <path fill-rule="evenodd"
              d="M9.53 2.22L9 1.69L7.94 2.75l.53.53 4 4H1.75v1.5h10.69l-4 4-1.06 1.06L9 14.31l5.07-5.07c.39-.39.39-1.03 0-1.42L9.53 2.22z" />
          </svg>
        </a>
      </div>
    </div>

    <!-- 右侧会话列表 -->
    <div class="lg:col-start-7 lg:col-span-11 xl:col-start-8">
      <div v-for="(session, i) in sessions" :key="i"
        class="grid grid-cols-11 gap-5 border-b border-[#343232c0] py-16 first:pt-0 last:border-0 last:pb-0">

        <div class="col-span-full lg:col-span-4 flex flex-col gap-6 items-start">
          <h3 class="text-3xl font-medium leading-none lg:tracking-[-0.04em]">{{ session.title }}</h3>
          <div class="text-[18px] font-mono uppercase text-gray-1000">{{ session.time }}</div>
        </div>
        <div class="mx-auto w-full px-16 grid lg:grid-cols-[repeat(18,1fr)] lg:gap-5">
          <div class="col-span-full lg:col-start-6 lg:col-span-6 flex flex-col gap-6">
            <p class="text-base text-gray-400 font-mono leading-normal">{{ session.description }}</p>

            <div class="flex items-center gap-4">
              <div class="size-9 rounded-full overflow-hidden bg-[#343232c0]">
                <img :src="session.avatar" :alt="session.speaker" class="object-cover w-full h-full">
              </div>
              <p class="text-base font-mono uppercase">
                {{ session.speaker }},
                <span class="text-gray-500 underline underline-offset-2 decoration-gray-600">{{ session.company
                  }}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const sessions = [
  {
    title: 'Real-time voice agents with ElevenLabs and AI SDK',
    time: '3:05 PM–3:25 PM',
    description: 'Voice is the most natural interface for AI, but building it is hard. This talk shows how you can use ElevenLabs APIs and Vercel\'s AI SDK to build real-time voice agents that listen, reason, and respond.',
    speaker: 'Alex Holt',
    company: 'ElevenLabs',
    avatar: '/third/alex-holt.avif',
  },
  {
    title: 'Building AI agents that generate full Next.js Apps',
    time: '3:30 PM–3:50 PM',
    description: 'Swap github.com for mintlify.com on any repo and get a full docs site generated by AI. This talk breaks down the agent harness built on Vercel Sandbox, from codebase analysis to parallel generation to verifying the output by actually building the Next.js site.',
    speaker: 'Nick Khami',
    company: 'Mintlify',
    avatar: '/third/mike_taylor_deepmind.avif',
  },
]
</script>